version: "3.1"

services:
  mysqldb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jojae
    ports:
      - 3306:3306
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: test-redis
    hostname: test
    ports:
      - 6379:6379
