version: "3.1"

services:
  mysql_5_7:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: jojae
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: test-redis
    hostname: test
    ports:
      - 6379:6379
