server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: jojae
  jpa:
    open-in-view: false
    database: mysql
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/jojae?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2
