spring:
  datasource:
    url: jdbc:h2:mem:jojae;MODE=MYSQL;
    username: test
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

external:
  user-service:
    host: 'https://randomuser.me'
  human-service:
    host: 'http://localhost:8080'
